version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo Running Maven build...
      - mvn -B package --file pom.xml
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_USERNAME/guess-number-app:latest .
  post_build:
    commands:
      - echo Pushing image to Docker Hub...
      - docker push $DOCKERHUB_USERNAME/guess-number-app:latest
artifacts:
  files:
    - target/*.jar
