apiVersion: apps/v1
kind: Deployment
metadata:
  name: guess-number-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guess-number-app
  template:
    metadata:
      labels:
        app: guess-number-app
    spec:
      containers:
      - name: tomcat
        image: rohannagcalsoft/guess-number-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
